package com.pereiraprive.beerlover;


import android.os.Bundle;
import android.support.v7.app.ActionBarActivity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;

import java.util.concurrent.ExecutionException;


public class UserAuth extends ActionBarActivity {

    private Button envoi;
    private TextView message;
    private EditText email, nickname;
    private String my_email= null, pseudo = null, token = null;
    private JSONObject json = null;
    private String content = null;

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Set the "beer_list" content
        setContentView(R.layout.user_auth);

        // Retrieves the objects
        envoi = (Button) findViewById(R.id.button_send);
        message = (TextView) findViewById(R.id.message);
        email = (EditText) findViewById(R.id.email);
        nickname = (EditText) findViewById(R.id.nickname);


        // if click, email and nickname are send to the server and we receive a token
        envoi.setOnClickListener(new View.OnClickListener() {

            public void onClick(View view) {
                //  Log.v("EditText", email.getText().toString());
                //  Log.v("EditText", nickname.getText().toString());
                // get the strings written in the app

                my_email = new String(email.getText().toString());
                pseudo = new String(nickname.getText().toString());

                try {
                    json = ConvertToJson(my_email, pseudo);
                    content = json.toString();
                    PostUserToken(content);
                }
                catch (JSONException e){}

                // Ends the view
                finish();

            }

        });

    }

    public JSONObject ConvertToJson (String email, String nickname) throws JSONException{

        JSONObject json = new JSONObject();
        JSONObject userJson = new JSONObject();
        userJson.put("nickname", nickname);
        userJson.put("email", email);
        json.put("user",userJson);
        return json;
    }

    // Saves the token in the phone memory
    private void SaveInMemory(String nomFichier, String monText) {

        // Saves the token in memory
        try {
            FileOutputStream fOut = openFileOutput(nomFichier, MODE_PRIVATE);
            fOut.write(monText.getBytes());
            fOut.close();
        }
        catch(FileNotFoundException e) {}
        catch (IOException e) {}

        // Shows to the user everything is all right
        Toast.makeText(getBaseContext(),"Compte bien renseigné !", Toast.LENGTH_SHORT).show();

    }

    // Gets the token generated by the server
    public void PostUserToken(String content) {

        String token = null;

        // Create a DownloadTask
        DownloadTask dlTask = new DownloadTask();

        // Downloads the content we want & gets the result

        dlTask.execute("POST", "http://binouze.fabrigli.fr/user.json", content);

        // Retrieves the result
        try {
            token = dlTask.get();
            System.out.println(token);
            SaveInMemory("BeerloverToken.txt", token);

        } catch (InterruptedException | ExecutionException e) {}

    }
}
